'use strict';
/**
 * Fluid type scale and spacing from the Krafter Lite template design system.
 * All values use clamp() so they scale smoothly between mobile and desktop.
 *
 * Usage:
 *   const TS = require('../references/type-scale');
 *   // OR via the builder:
 *   const ts = b.typeScale();   // registers global vars + returns $variable()$ refs
 *   const ss = b.spaceScale();
 */

// Font sizes: desktop clamp(min, preferred, max)
exports.TYPE = {
  '3xl': 'clamp(2.25rem, 2rem + 1vw, 3rem)',          // H1
  '2xl': 'clamp(1.875rem, 1.6rem + 0.7vw, 2.25rem)',  // H2
  xl:    'clamp(1.5rem, 1.3rem + 0.6vw, 1.875rem)',    // H3
  m:     'clamp(1rem, 0.9rem + 0.4vw, 1.25rem)',       // body
};

// Spacing: section padding, module margins, card padding
exports.SPACE = {
  l: 'clamp(1.5rem, 1rem + 1vw, 2.5rem)',
  m: 'clamp(1rem, 0.6rem + 0.8vw, 1.5rem)',
  s: 'clamp(0.5rem, 0.3rem + 0.6vw, 1rem)',
};

// Stable global variable IDs — distinct from Krafter Lite's opaque gvid-* slugs
// so pages generated by this tool have readable, consistent IDs across any site.
exports.GVID = {
  text3xl: 'gvid-dts-text-3xl',
  text2xl: 'gvid-dts-text-2xl',
  textXl:  'gvid-dts-text-xl',
  textM:   'gvid-dts-text-m',
  spaceL:  'gvid-dts-space-l',
  spaceM:  'gvid-dts-space-m',
  spaceS:  'gvid-dts-space-s',
};
